### ISSUE TITLE
Update compiler workarounds for MSVC 2022

### ISSUE THREAD

**Issue by NancyLi1013** [mosra/corrade#124]
Hi @mosra,

I'm a member of Microsoft vcpkg team. In our latest internal test, `corrade `installation failed with following error:

```
FAILED: src/Corrade/Utility/CMakeFiles/CorradeUtilityObjects.dir/TweakableParser.cpp.obj 
"E:\Visual Studio\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe"   /TP -DCORRADE_IS_DEBUG_BUILD -DCorradeUtilityObjects_EXPORTS -DNOMINMAX -DUNICODE -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -IC:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src -IC:\vcpkg_1011\vcpkg\buildtrees\corrade\x64-windows-dbg\src /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /wd4251 /wd4244 /wd4267 /wd4351 /wd4373 /wd4510 /wd4610 /wd4512 /wd4661 /wd4702 /wd4706 /wd4800 /wd4910 /showIncludes /Fosrc\Corrade\Utility\CMakeFiles\CorradeUtilityObjects.dir\TweakableParser.cpp.obj /Fdsrc\Corrade\Utility\CMakeFiles\CorradeUtilityObjects.dir\ /FS -c C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(40): error C2666: '+': 2 overloads have similar conversions
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(40): note: could be 'built-in C++ operator+(bool, int)'
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(40): note: or       'built-in C++ operator+(const T, __int64)'
        with
        [
            T=const char
        ]
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(40): note: while trying to match the argument list '(Corrade::Containers::ArrayView<const char>, int)'
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(40): error C2440: 'return': cannot convert from 'initializer list' to 'std::pair<const char *,int>'
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(40): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(42): error C2666: '+': 2 overloads have similar conversions
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(42): note: could be 'built-in C++ operator+(bool, int)'
C:\vcpkg_1011\vcpkg\buildtrees\corrade\src\v2020.06-2e11614b58\src\Corrade\Utility\TweakableParser.cpp(42): note: or       'built-in C++ operator+(const T, __int64)'
        with
        [
            T=const char
        ]
```

After investigation, we found that it was caused by  the value of `CMAKE_CXX_COMPILER_VERSION`. It has become `19.31.30710.95` in interval version of Visual Studio, which is out of range 19.30 in Visual Studio 2019.

Seems `corrade `needs to support Visual Studio 2022. Could you please help look into and confirm this issue?

Thanks in advance.

**Comment by Auburn** [comment]
To bump this, looks like AppVeyor CI has added VS 2022 support now

**Comment by mosra** [comment]
As of 00cfbbb9f8262919fe337e7d9422dbc59910adbe there's a new `CORRADE_MSVC_COMPATIBILITY` option which supersedes `CORRADE_MSVC2019_COMPATIBILITY` (removed in 316205eddadf735d40d64d2c290ca82d0243eb11), and is enabled by default on MSVC 2019+. This option now covers everything that's fixed by `/permissive-` -- if you set this compiler flag for all files, you can disable `CORRADE_MSVC_COMPATIBILITY` and live workaround-free on MSVC 2019 and newer. For 2017 and older there's still the `CORRADE_MSVC{2017,2015}_COMPATIBILITY` and `/permissive-` makes it do weird things, so please don't try setting the flag there.

Commits a72eea841efdf434bd33cd2003abb12ce81e8458, 2fa0ba175fc738c000d8dddefcbe1d6e70bac75e, mosra/magnum@acc17f063a8f4d46e4420d9aaf95e1ed1825f45f, mosra/magnum@4d574b007387b483e8fe61265a508c1b61e06fa0, mosra/magnum@efcdfc122170f55f4b5eedfcbb393b45f76b80f1 and mosra/magnum-plugins@18a1d6012f6d611c34fcc718751aa0965ef3a632 make Corrade, Magnum and Magnum Plugins work with both MSVC 2019 and 2022, both with and without the `/permissive-` flag. The [CI now also tests for `/permissive-` builds](https://magnum.graphics/build-status/) on 2019 and 2022, to catch issues happening only with this flag enabled. Other repositories don't have any known workarounds for MSVC 2019 so I expect them to work with 2022 without issues, CI builds for these will be added over the next days/weeks.
