### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [mosra/corrade#47]
Some parameters (like “[${CMAKE_CURRENT_BINARY_DIR}/configure.h](https://github.com/mosra/corrade/blob/bd807d31c2a5797424003ad6118362cbda436330/src/Corrade/CMakeLists.txt#L38 "Update candidate")”) are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Language-Syntax#cmake-splits-arguments-unless-you-use-quotation-marks-or-escapes "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by mosra** [comment]
You opened this exact issue five years ago on the magnum repository, don't you remember? ;) Because I do: https://github.com/mosra/magnum/issues/24

If you look at your issue from 2013, there I proved that **quoting is not necessary** — CMake is not Unix shell, it will correctly preserve the space in variable substitutions. And to answer your second question from there — no, I don't plan bothering with paths containing semicolons. Unlike spaces, that's too hard to fix and not worth spending time with.
